linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - megacheck
    - golint
    - govet
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - stylecheck
    - gochecknoinits
    - scopelint
    - gocritic
    - golint
    - nakedret
    - gosimple
    - prealloc

  fast: false


run:
  tests: false
  modules-download-mode: vendor
  skip-dirs:
    - vendor
  concurrency: 4

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
  exclude-use-default: false

service:
  golangci-lint-version: 1.34.x
