version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - revive
    - govet
    - unconvert
    - staticcheck
    - unused
    - gosec
    - misspell
    - unparam
    - ineffassign
    - gochecknoinits
    - copyloopvar
    - gocritic
    - nakedret
    - prealloc
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
  exclusions:
    paths:
      - vendor
    rules:
      - text: "weak cryptographic primitive"
        linters:
          - gosec
      - text: "package-comments: should have a package comment"
        linters:
          - revive

run:
  concurrency: 4
